### ISSUE TITLE
【翻译认领】 design/Semantics.md

### ISSUE THREAD

**Issue by weimengxi** [WebAssembly-cn/website#15]
**Web UR**L: http://webassembly.org.cn/docs/semantics

**File Path**: design/Semantics.md.

**Estimated**: 1 Week.

**Status**: In progress.

**Comment by unbug** [comment]
@weimengxi 你已经翻译完了对吗？一个坏消息，你应该翻译的是
**File Path**: [design/Semantics.md](https://github.com/WebAssembly-cn/design/blob/5bca2107ed90a8168a87629598f09a7d51ed048c/Semantics.md). 一个好消息是改过去来应该是各种复制粘贴就好啦，然后按指南里的 Review 流程提个 Pull request.

**Comment by unbug** [comment]
@weimengxi 我更新了[翻译指南 WIKI](https://github.com/WebAssembly-cn/website/wiki/%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E7%BF%BB%E8%AF%91%E5%BF%85%E8%AF%BB%E6%8C%87%E5%8D%97)，你翻译的文件在[/WebAssembly-cn/design](https://github.com/WebAssembly-cn/design) repo 里，你需要 fork 的是它。具体流程看 WIKI。

**Comment by weimengxi** [comment]
@unbug Ok, gotcha.
