### ISSUE TITLE
【翻译认领】design/FAQ.md

### ISSUE THREAD

**Issue by hijiangtao** [WebAssembly-cn/website#23]
Web URL: http://webassembly.org.cn/docs/faq/

File Path: design/FAQ.md

Estimated: 1 Week.

Status: In progress.

**Comment by juzhiyuan** [comment]
Sorry, but the link has broken.

**Comment by hijiangtao** [comment]
Draft is done with PR. https://github.com/WebAssembly-cn/design/pull/10

**Comment by hijiangtao** [comment]
Done with https://github.com/WebAssembly-cn/design/pull/10
